{
 "title": "Graphcast Network monitor",
 "time": { "from": "2023-10-06T15:20:43.110Z", "to": "2023-10-06T15:24:31.211Z" },
 "panels": [
  {
   "title": "Receive and pruned",
   "type": "timeseries",
   "description": "The rate of receiving and pruning messages based on _rate_interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(graphcast_listener_radio_pruned_messages[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(graphcast_listener_radio_received_messages[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sender stats",
   "type": "table",
   "description": "For each sender account, show their distinct deployment and message counts in store",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "rows",
     "endTimePath": "endTime",
     "queryText": "query {\n  rows{\n    message{\n        identifier\n        graphAccount\n        nonce\n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Stored messages",
   "type": "table",
   "description": "Query db for a quick view of recent messages",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "rows",
     "endTimePath": "endTime",
     "queryText": "query {\n  rows{\n    id\n    message{\n     identifier\n      nonce\n      graphAccount\n       payload{\n      \tcontent\n       }  \n    }\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Received and cached volume",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graphcast_listener_radio_received_messages",
     "legendFormat": "__auto"
    },
    {
     "expr": "graphcast_listener_radio_cached_messages",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}